### ISSUE TITLE
不能打开配置文件

### ISSUE THREAD

**Issue by Hendric290** [zhouforme0318/GAMPII-GOOD#1]
E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
*** ERROR(PreProcess::ReadCfgFile): open configure file gamp_good.cfg FAILED!

第一行就报错了，也不知道怎么办。Looking forward your earlier reply, thanks

**Comment by FFFFFG-IGG** [comment]
> E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
> *** ERROR(PreProcess::ReadCfgFile): open configure file gamp_good.cfg FAILED!
> 
> 第一行就报错了，也不知道怎么办。Looking forward your earlier reply, thanks

你好！你需要将配置文件与执行文件（exe）放入同一目录下才可以正常执行！否则你需要输入run_GAMP_GOOD gamp_good.cfg（完整路径）

**Comment by Hendric290** [comment]
谢谢您的回复。

E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
*** INFO(FtpUtil::GetNav): failed to download broadcast ephemeris file brdm0320.21p
系统找不到指定的文件。
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210320000_01D_*_ORB.SP3.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210320000_01D_*_ORB.SP3.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise orbit file grm21431.sp3
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210320000_01D_*_CLK.CLK.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210320000_01D_*_CLK.CLK.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise clock file grm21431.clk
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210310000_01D_*_ORB.SP3.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210310000_01D_*_ORB.SP3.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise orbit file grm21430.sp3
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210310000_01D_*_CLK.CLK.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210310000_01D_*_CLK.CLK.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise clock file grm21430.clk
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210330000_01D_*_ORB.SP3.gz: No such file or directory
系统找不到指定的文件。

1. 以上是输入的命令和报错记录。
2. 我是把 Example_Win 文件夹下面的配置文件复制到执行文件同一目录的，不能运行；
3. 使用完整路径依然error，请参照报错记录。

**Comment by Hendric290** [comment]
> > E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
> > *** ERROR(PreProcess::ReadCfgFile): open configure file gamp_good.cfg FAILED!
> > 第一行就报错了，也不知道怎么办。Looking forward your earlier reply, thanks
> 
> 你好！你需要将配置文件与执行文件（exe）放入同一目录下才可以正常执行！否则你需要输入run_GAMP_GOOD gamp_good.cfg（完整路径）

**Comment by Hendric290** [comment]
> > > E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
> > > *** ERROR(PreProcess::ReadCfgFile): open configure file gamp_good.cfg FAILED!
> > > 第一行就报错了，也不知道怎么办。Looking forward your earlier reply, thanks
> > 
> > 
> > 你好！你需要将配置文件与执行文件（exe）放入同一目录下才可以正常执行！否则你需要输入run_GAMP_GOOD gamp_good.cfg（完整路径）

谢谢您的回复。

E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
*** INFO(FtpUtil::GetNav): failed to download broadcast ephemeris file brdm0320.21p
系统找不到指定的文件。
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210320000_01D_*_ORB.SP3.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210320000_01D_*_ORB.SP3.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise orbit file grm21431.sp3
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210320000_01D_*_CLK.CLK.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210320000_01D_*_CLK.CLK.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise clock file grm21431.clk
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210310000_01D_*_ORB.SP3.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210310000_01D_*_ORB.SP3.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise orbit file grm21430.sp3
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210310000_01D_*_CLK.CLK.gz: No such file or directory
系统找不到指定的文件。
GRG0MGXFIN_20210310000_01D_*_CLK.CLK.Z: No such file or directory
系统找不到指定的文件。
*** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise clock file grm21430.clk
'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
GRG0MGXFIN_20210330000_01D_*_ORB.SP3.gz: No such file or directory
系统找不到指定的文件。

1. 以上是输入的命令和报错记录。
2. 我是把 Example_Win 文件夹下面的配置文件复制到执行文件同一目录的，不能运行；
3. 使用完整路径依然error，请参照报错记录。

**Comment by FFFFFG-IGG** [comment]
> > > > E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
> > > > *** ERROR(PreProcess::ReadCfgFile): open configure file gamp_good.cfg FAILED!
> > > > 第一行就报错了，也不知道怎么办。Looking forward your earlier reply, thanks
> > > 
> > > 
> > > 你好！你需要将配置文件与执行文件（exe）放入同一目录下才可以正常执行！否则你需要输入run_GAMP_GOOD gamp_good.cfg（完整路径）
> 
> 谢谢您的回复。
> 
> E:\GAMPII-GOOD-master\bin\Win>run_GAMP_GOOD gamp_good.cfg
> 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> *** INFO(FtpUtil::GetNav): failed to download broadcast ephemeris file brdm0320.21p
> 系统找不到指定的文件。
> 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> GRG0MGXFIN_20210320000_01D___ORB.SP3.gz: No such file or directory 系统找不到指定的文件。 GRG0MGXFIN_20210320000_01D___ORB.SP3.Z: No such file or directory 系统找不到指定的文件。 *** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise orbit file grm21431.sp3 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 GRG0MGXFIN_20210320000_01D___CLK.CLK.gz: No such file or directory 系统找不到指定的文件。 GRG0MGXFIN_20210320000_01D___CLK.CLK.Z: No such file or directory 系统找不到指定的文件。 *** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise clock file grm21431.clk 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 GRG0MGXFIN_20210310000_01D___ORB.SP3.gz: No such file or directory 系统找不到指定的文件。 GRG0MGXFIN_20210310000_01D___ORB.SP3.Z: No such file or directory 系统找不到指定的文件。 *** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise orbit file grm21430.sp3 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 GRG0MGXFIN_20210310000_01D___CLK.CLK.gz: No such file or directory 系统找不到指定的文件。 GRG0MGXFIN_20210310000_01D___CLK.CLK.Z: No such file or directory 系统找不到指定的文件。 *** INFO(FtpUtil::GetOrbClk): failed to download MGEX precise clock file grm21430.clk 'D:\data\thirdParty\wget' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 GRG0MGXFIN_20210330000_01D_*_ORB.SP3.gz: No such file or directory
> 系统找不到指定的文件。
> 
> 1. 以上是输入的命令和报错记录。
> 2. 我是把 Example_Win 文件夹下面的配置文件复制到执行文件同一目录的，不能运行；
> 3. 使用完整路径依然error，请参照报错记录。

出现这个问题是你没有修改配置文件，你需要对编辑配置文件进行编辑，如下图：
![image](https://user-images.githubusercontent.com/59271400/131324366-3807c74c-1631-4a5a-9869-cfee9c67784e.png)
1.设置数据储存路径（设置自己的数据储存路径）
2.设置第三方软件路径（即wget等可执行文件的路径，这些都在thirdparty文件目录下）
此外，建议阅读doc文件中的说明文档以进行正确的数据下载操作。
